[project]
name = "xmpp-utilities"
version = "1.2.0"
description = "An XMPP bot with diagnostics and monitoring tools"
readme = "README.md"
license = "0BSD"
license-files = ["LICENSE"]
authors = [
    { name = "FSKY", email = "development@fsky.io" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: No Input/Output (Daemon)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Communications",
    "Topic :: Communications :: Chat",
    "Topic :: Internet :: XMPP",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators"
]
keywords = ["xmpp", "xmpp bot", "slixmpp", "bot"]
requires-python = ">=3.13"
dependencies = [
    "dnspython[dnssec]>=2.8.0",
    "slixmpp>=1.12.0",
]

[project.urls]
Homepage = "https://fsky.io/projects/xmpp-utilities/"
Repository = "https://foundry.fsky.io/fsky/xmpp-utilities.git"
Issues = "https://foundry.fsky.io/fsky/xmpp-utilities/issues"

[project.scripts]
xmpp-utilities = "xmpp_utilities.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"src/xmpp_utilities/avatar.png" = "xmpp_utilities/avatar.png"

[[tool.uv.index]]
name = "foundry"
url = "https://foundry.fsky.io/api/packages/fsky/pypi/simple/"
publish-url = "https://foundry.fsky.io/api/packages/fsky/pypi/"
explicit = true
