[project]
name = "xmpp-utilities"
version = "1.1.0"
readme = "README.md"
license = "Unlicense"
license-files = ["LICENSE"]
authors = [
    { name = "Telepath", email = "development@telepath.im" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: No Input/Output (Daemon)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Communications",
    "Topic :: Communications :: Chat",
    "Topic :: Internet :: XMPP",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators"
]
keywords = ["xmpp", "xmpp bot", "slixmpp", "bot"]
requires-python = ">=3.13"
dependencies = [
    "dnspython>=2.8.0",
    "slixmpp>=1.12.0",
]

[project.urls]
Homepage = "https://telepath.im/projects/xmpp-utilities/"
Repository = "https://foundry.fsky.io/telepath/xmpp-utilities.git"
Issues = "https://foundry.fsky.io/telepath/xmpp-utilities/issues"

[project.scripts]
xmpp-utilities = "xmpp_utilities.__main__:main"

[[tool.uv.index]]
name = "foundry"
url = "https://foundry.fsky.io/api/packages/telepath/pypi/simple/"
publish-url = "https://foundry.fsky.io/api/packages/telepath/pypi/"
explicit = true
